### ISSUE TITLE
Bot joins VC but does not play the mp3 file

### ISSUE THREAD

**Issue by RuslanTL** [discordjs/voice#204]
I'm currently testing a basic music feature for my bot where it plays a local audio file once it joins the voice chat. However, even though the bot joins the voice channel, it doesn't play anything. The path to the audio file is correct, I'm not sure what could be causing the issue. 

```js
const path = require('path');
const {
    AudioPlayerStatus,
    StreamType,
    createAudioPlayer,
    createAudioResource,
    joinVoiceChannel,
} = require('@discordjs/voice');
const { SlashCommandBuilder } = require('@discordjs/builders');
const { generateDependencyReport } = require('@discordjs/voice');
const { Client, Intents, Collection } = require('discord.js');
const client = new Client({
    intents:	[Intents.FLAGS.GUILD_VOICE_STATES] 
});
module.exports = {
  data: new SlashCommandBuilder()
        .setName('join')
        .setDescription('join voice channel'),
  async execute(interaction) {
        voiceChannel = interaction.member.voice.channel;
        guild = interaction.member.guild;
        const connection = joinVoiceChannel({ 
            channelId: voiceChannel.id,
            guildId: guild.id,
            adapterCreator: guild.voiceAdapterCreator,
        });
        const resource = createAudioResource(path.resolve('commands/audiotest/resonance.mp3'));
        const player = createAudioPlayer();
        connection.subscribe(player);
        player.play(resource);
        interaction.reply("joined!")
        console.log(generateDependencyReport());
        player.on(AudioPlayerStatus.Idle, () => connection.destroy());
    }
};

```

**Further details:**
AudioResource, AudioPlayer and Dependency Report log: https://hastebin.com/exuxoxohim.yaml

- @discordjs/voice version: 0.6.0
- Node.js version: 16.8.0
- Operating system: Windows 10
- Priority this issue should have : I haven't been able to find a fix for this for days but i guess it's not very important

**Comment by TomJanse** [comment]
I'm not sure if I'm allowed to comment this, but I have the same issue and I have seen a lot of other people having this issue. I would argue the priority should be pretty high.

Perhaps notable is that, for me, the player does enter the Playing state but no audio is being played.

**Comment by x5engine** [comment]
yeah bro I kept trying to so much and I have the same issue!! everything installed! code from the docs! https://discordjs.guide/voice/life-cycles.html#subscribing-to-individual-events


but no audio playing

says Playback has started!
but nothing is playing!

**Comment by killer069** [comment]
@x5engine @RuslanTL @TomJanse 

I think if you have ffmpeg-static, then you will 100% face this issue. Try to use global ffmpeg instead.

Remove ffmpeg-static completely and then try playing audio by downloading actual ffmpeg from [here](https://ffmpeg.org/)

**Comment by x5engine** [comment]
> @x5engine @RuslanTL @TomJanse 
> 
> I think if you have ffmpeg-static, then you will 100% face this issue. Try to use global ffmpeg instead.
> 
> Remove ffmpeg-static completely and then try playing audio by downloading actual ffmpeg from [here](https://ffmpeg.org/)

I have both installed on debian on GCP

I didn't have ffmpeg-static installed and it didn't work.


Please visit our discord and try our both 

On https://discord.gg/WfqzZZdr38

No matter what the audio is not played even if the state says it is playing!

No errors or warning no matter what!

I even added ffmpeg to /use/local/bin if that's needed since ffmpeg is already automatically added to PATH

But it has user as root?

Running the bot on pm2

Node v16

Please help us

**Comment by RuslanTL** [comment]
> 
> 
> @x5engine @RuslanTL @TomJanse
> 
> I think if you have ffmpeg-static, then you will 100% face this issue. Try to use global ffmpeg instead.
> 
> Remove ffmpeg-static completely and then try playing audio by downloading actual ffmpeg from [here](https://ffmpeg.org/)

i've installed ffmpeg and set my PATH to it, but im getting errors that i don't have ffmpeg:

`FFmpeg
- not found
--------------------------------------------------
Error: FFmpeg/avconv not found!
    at Function.getInfo (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:143:11)
    at Function.create (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:156:38)
    at new FFmpeg (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:45:27)
    at Object.transformer (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js:144:29)
    at D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:60
    at Array.map (<anonymous>)
    at createAudioResource (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:41)
    at Object.execute (D:\rustl\Desktop\MoyaiBot\commands\join.js:31:26)
    at Client.<anonymous> (D:\rustl\Desktop\MoyaiBot\index.js:54:17)
    at Client.emit (node:events:394:28)
`
did i install it wrong or do i need to do something else? sorry im new

**Comment by x5engine** [comment]
> > 
> > 
> > @x5engine @RuslanTL @TomJanse
> > 
> > I think if you have ffmpeg-static, then you will 100% face this issue. Try to use global ffmpeg instead.
> > 
> > Remove ffmpeg-static completely and then try playing audio by downloading actual ffmpeg from [here](https://ffmpeg.org/)
> 
> i've installed ffmpeg and set my PATH to it, but im getting errors that i don't have ffmpeg:
> 
> ```
> FFmpeg
> - not found
> --------------------------------------------------
> Error: FFmpeg/avconv not found!
>     at Function.getInfo (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:143:11)
>     at Function.create (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:156:38)
>     at new FFmpeg (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:45:27)
>     at Object.transformer (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js:144:29)
>     at D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:60
>     at Array.map (<anonymous>)
>     at createAudioResource (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:41)
>     at Object.execute (D:\rustl\Desktop\MoyaiBot\commands\join.js:31:26)
>     at Client.<anonymous> (D:\rustl\Desktop\MoyaiBot\index.js:54:17)
>     at Client.emit (node:events:394:28)
> ```
> did i install it wrong or do i need to do something else? sorry im new

Where did you get this error from?

**Comment by RuslanTL** [comment]
> 
> 
> > > @x5engine @RuslanTL @TomJanse
> > > I think if you have ffmpeg-static, then you will 100% face this issue. Try to use global ffmpeg instead.
> > > Remove ffmpeg-static completely and then try playing audio by downloading actual ffmpeg from [here](https://ffmpeg.org/)
> > 
> > 
> > i've installed ffmpeg and set my PATH to it, but im getting errors that i don't have ffmpeg:
> > ```
> > FFmpeg
> > - not found
> > --------------------------------------------------
> > Error: FFmpeg/avconv not found!
> >     at Function.getInfo (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:143:11)
> >     at Function.create (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:156:38)
> >     at new FFmpeg (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:45:27)
> >     at Object.transformer (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js:144:29)
> >     at D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:60
> >     at Array.map (<anonymous>)
> >     at createAudioResource (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:41)
> >     at Object.execute (D:\rustl\Desktop\MoyaiBot\commands\join.js:31:26)
> >     at Client.<anonymous> (D:\rustl\Desktop\MoyaiBot\index.js:54:17)
> >     at Client.emit (node:events:394:28)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > did i install it wrong or do i need to do something else? sorry im new
> 
> Where did you get this error from?

in git bash after i used the /join command

**Comment by killer069** [comment]
@RuslanTL @x5engine 

Debug your [dependencies](https://discordjs.guide/voice/#debugging-dependencies) and send it here.

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL @x5engine
> 
> Debug your [dependencies](https://discordjs.guide/voice/#debugging-dependencies) and send it here.

```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.6.0
- prism-media: 1.3.2

Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5

FFmpeg
- not found
--------------------------------------------------
```

**Comment by killer069** [comment]
@RuslanTL 

Where is ffmpeg??

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL
> 
> Where is ffmpeg??

well i uninstalled ffmpeg-static as you said and then tried installing github globally and then added it to my path. idk why it did not work

**Comment by killer069** [comment]
@RuslanTL 

Linux or windows ??

**Comment by x5engine** [comment]
here is mine on linux debian

0|index    | Opus Libraries
0|index    | - @discordjs/opus: not found
0|index    | - opusscript: 0.0.8
0|index    | 
0|index    | Encryption Libraries
0|index    | - sodium: not found
0|index    | - libsodium-wrappers: not found
0|index    | - tweetnacl: 1.0.3
0|index    | 
0|index    | FFmpeg
0|index    | - version: 4.4-static https://johnvansickle.com/ffmpeg/ 
0|index    | - libopus: yes
0|index    | --------------------------------------------------

**Comment by killer069** [comment]
@x5engine 

As told earlier, ffmpeg static versions have some issues. Switch to global ffmpeg

**Comment by x5engine** [comment]
I already uninstalled it!

here is my package.json

  "dependencies": {
    "@discordjs/voice": "^0.6.0",
    "@google-cloud/text-to-speech": "^3.3.0",
    "axios": "^0.21.4",
    "discord.js": "^13.1.0",
    "fs": "^0.0.1-security",
    "ipfs-api": "^26.1.2",
    "opusscript": "^0.0.8",
    "util": "^0.12.4",
    "uuid": "^8.3.2",
    "ytdl-core": "^4.9.1"
  },

@killer069

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL
> 
> Linux or windows ??

Windows 10

**Comment by killer069** [comment]
@RuslanTL 

> Windows 10

Do [this] and remove ffmpeg-static (if any) [ also check by `npm ls ffmpeg-static` ]

@x5engine 

Just make sure you don't have ffmpeg-static folder inside node_modules folder.

And install ffmpeg like [this](https://linuxize.com/post/how-to-install-ffmpeg-on-debian-9/)

**Comment by x5engine** [comment]
> @RuslanTL 
> 
> > Windows 10
> 
> Do [this](https://www.wikihow.com/Install-FFmpeg-on-Windows) and remove **ffmpeg-static** (if any) [ also check by `npm ls ffmpeg-static` ]
> 
> @x5engine 
> 
> Just make sure you don't have **ffmpeg-static** folder inside `node_modules` folder.
> 
> And install ffmpeg like [this](https://linuxize.com/post/how-to-install-ffmpeg-on-debian-9/)

Yeah I already installed like that!

I already did npm uninstall -S ffmpeg-static

But I'll check the node modules folder for it.

This installation part should be way more documented!

Btw will voices work on the new spaces?

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL
> 
> > Windows 10
> 
> Do [this](https://www.wikihow.com/Install-FFmpeg-on-Windows) and remove **ffmpeg-static** (if any) [ also check by `npm ls ffmpeg-static` ]
> 
> @x5engine
> 
> Just make sure you don't have **ffmpeg-static** folder inside `node_modules` folder.
> 
> And install ffmpeg like [this](https://linuxize.com/post/how-to-install-ffmpeg-on-debian-9/)

i tried that and it still fails
```js
$ node index.js
MoyaiBot ready!
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.6.0
- prism-media: 1.3.2

Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5

FFmpeg
- not found
--------------------------------------------------
Error: FFmpeg/avconv not found!
    at Function.getInfo (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:143:11)
    at Function.create (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:156:38)
    at new FFmpeg (D:\rustl\Desktop\MoyaiBot\node_modules\prism-media\src\core\FFmpeg.js:45:27)
    at Object.transformer (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js:144:29)
    at D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:60
    at Array.map (<anonymous>)
    at createAudioResource (D:\rustl\Desktop\MoyaiBot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:156:41)
    at Object.execute (D:\rustl\Desktop\MoyaiBot\commands\join.js:31:26)
    at Client.<anonymous> (D:\rustl\Desktop\MoyaiBot\index.js:54:17)
    at Client.emit (node:events:394:28)
```
and ffmpeg is in my PATH 
![image](https://user-images.githubusercontent.com/53999108/133891322-b2190117-a3cd-4eec-a774-06d8467e0068.png)

**Comment by killer069** [comment]
@RuslanTL 

Try to run `ffmpeg -version` in cmd and see if you got ffmpeg working or not.

@x5engine 

I don't understand by that question. Can you please elaborate ?

Check modules folder and try to remove ffmpeg-static completely and run dependencies log again to see if ffmpeg-static is removed completely or not.

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL
> 
> Try to run `ffmpeg -version` in cmd and see if you got ffmpeg working or not.
> 
> @x5engine
> 
> I don't understand by that question. Can you please elaborate ?
> 
> Check modules folder and try to remove ffmpeg-static completely and run dependencies log again to see if ffmpeg-static is removed completely or not.

```js
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```
seems to be working

**Comment by killer069** [comment]
@RuslanTL 

Console log dependencies again.

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL
> 
> Console log dependencies again.
```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.6.0
- prism-media: 1.3.2

Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5

FFmpeg
- not found
--------------------------------------------------
```
same as before

**Comment by killer069** [comment]
@RuslanTL 

So try creating a new folder and do `npm init -y` and install discordjs/voice there and log dependencies.

**Comment by x5engine** [comment]
you were right I deleted that folder and here is the deps now


```
0|index    | 
0|index    | Opus Libraries
0|index    | - @discordjs/opus: not found
0|index    | - opusscript: 0.0.8
0|index    | 
0|index    | Encryption Libraries
0|index    | - sodium: not found
0|index    | - libsodium-wrappers: not found
0|index    | - tweetnacl: 1.0.3
0|index    | 
0|index    | FFmpeg
0|index    | - version: 3.2.15-0+deb9u4
0|index    | - libopus: yes
0|index    | --------------------------------------------------
```

**Comment by x5engine** [comment]
now same issue no sound!

first try i get playback started and nothing plays

but the second feature i have this error

```

0|index  | AbortError: The operation was aborted
0|index  |     at abortListener (node:events:842:14)
0|index  |     at EventTarget.<anonymous> (node:events:878:47)
0|index  |     at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:559:20)
0|index  |     at EventTarget.dispatchEvent (node:internal/event_target:504:26)
0|index  |     at abortSignal (node:internal/abort_controller:97:10)
0|index  |     at AbortController.abort (node:internal/abort_controller:122:5)
0|index  |     at Timeout.<anonymous> (/home/hqmetalgearsolide/lebot/node_modules/@discordjs/voice/dist/util/abortAfter.js:10:41)
0|index  |     at listOnTimeout (node:internal/timers:557:17)
0|index  |     at processTimers (node:internal/timers:500:7) {
0|index  |   code: 'ABORT_ERR'
```

**Comment by killer069** [comment]
@x5engine 

This issue is related with #199 . So I don't have any ideas, why this thing happened ? So can't help. Sorry

**Comment by RuslanTL** [comment]
> 
> 
> @RuslanTL
> 
> So try creating a new folder and do `npm init -y` and install discordjs/voice there and log dependencies.

```
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.6.0
- prism-media: 1.3.2

Opus Libraries
- @discordjs/opus: 0.5.3
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: 0.14.5

FFmpeg
- version: 4.4-full_build-www.gyan.dev
- libopus: yes
--------------------------------------------------
```
everything is here now, the ffmpeg is global but my bot still does not play anything

**Comment by FishMissile** [comment]
I seem to be having the same issue. I've tried everything suggested here and I'm still not getting any sound.

**Comment by FishMissile** [comment]
Switched to release build of ffmpeg. still nothing.

```
Core Dependencies
- @discordjs/voice: 0.6.0
- prism-media: 1.3.2

Opus Libraries
- @discordjs/opus: not found
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: not found

FFmpeg
- version: 4.4-essentials_build-www.gyan.dev
- libopus: yes
```

**Comment by killer069** [comment]
@RuslanTL 

Now See if your path.resolve is correct or not.

**Comment by relianamnguyen** [comment]
I'm facing this error too.
Error:
```
AudioPlayerError: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writevGeneric (node:internal/stream_base_commons:143:3)
    at Socket._writeGeneric (node:net:778:11)
    at Socket._writev (node:net:787:8)
    at doWrite (node:internal/streams/writable:406:12)
    at clearBuffer (node:internal/streams/writable:561:5)
    at onwrite (node:internal/streams/writable:461:7)
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:106:10) {
  resource: AudioResource {
    playbackDuration: 0,
    started: false,
    silenceRemaining: -1,
    edges: [ [Object], [Object] ],
    playStream: OggDemuxer {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      _remainder: null,
      _head: null,
      _bitstream: null,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null
    },
    metadata: null,
    silencePaddingFrames: 5,
    audioPlayer: AudioPlayer {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      subscribers: [Array],
      _state: [Object],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    }
  }
}
Audio player transitioned from buffering to idle
```

Dependency report: 
```
Core Dependencies                             
- @discordjs/voice: 0.6.0                     
- prism-media: 1.3.2                          
                                              
Opus Libraries                                
- @discordjs/opus: 0.6.0                      
- opusscript: not found                       
                                              
Encryption Libraries                          
- sodium: not found                           
- libsodium-wrappers: 0.7.9                   
- tweetnacl: not found                        
                                              
FFmpeg                                        
- version: 4.4-essentials_build-www.gyan.dev  
- libopus: yes                                
```

**Comment by x5engine** [comment]
any updates on this or how to debug it?

**Comment by killer069** [comment]
@FishMissile @x5engine 

Send your playing command codes in pastebin or sourcebin or hastebin

**Comment by x5engine** [comment]
> @FishMissile @x5engine 
> 
> Send your playing command codes in pastebin or sourcebin or hastebin

What playing command?

I have this coded on nodejs running in pm2

**Comment by StefansArya** [comment]
In my case, I need to change the server region
`Edit Channel -> Region Override`

Well, it was pretty simple and I couldn't believe it was the solution tbh 😄

**Comment by ThreonX** [comment]
Same issue here, I found the audio player enters AutoPaused state, and VoiceConnection is stuck in Signaling state. My code is similar to Authors.

Here are some console logs:

`Connection transitioned from signalling to signalling
Connection transitioned from signalling to signalling
Audio player transitioned from buffering to playing
Audio player transitioned from playing to autopaused
`

**Comment by killer069** [comment]
@ThreonX 

You are missing `GUILD_VOICE_STATES` intent.

**Comment by x5engine** [comment]
> `Edit Channel -> Region Override`

How did you change this region? where? I cant edit a voice channel settings

**Comment by x5engine** [comment]
I have this





const intents = new Discord.Intents(32767);

const discordClient = new Discord.Client({ intents });

  const resource = createAudioResource('./Song' + randomId + '.mp3', {
      inputType: StreamType.Arbitrary,
  });
  player.play(resource);
  try {
      await entersState(player, AudioPlayerStatus.Playing, 5_000);
      // The player has entered the Playing state within 5 seconds
      console.log('Playback has started!');
  } catch (error) {
      // The player has not entered the Playing state and either:
      // 1) The 'error' event has been emitted and should be handled
      // 2) 5 seconds have passed
      console.error(error);
  }

**Comment by killer069** [comment]
> I have this
> 
> const intents = new Discord.Intents(32767);
> 
> const discordClient = new Discord.Client({ intents });
> 
> const resource = createAudioResource('./Song' + randomId + '.mp3', {
> inputType: StreamType.Arbitrary,
> });
> player.play(resource);
> try {
> await entersState(player, AudioPlayerStatus.Playing, 5_000);
> // The player has entered the Playing state within 5 seconds
> console.log('Playback has started!');
> } catch (error) {
> // The player has not entered the Playing state and either:
> // 1) The 'error' event has been emitted and should be handled
> // 2) 5 seconds have passed
> console.error(error);
> }

Where is connection.subscribe ??

**Comment by killer069** [comment]
> > `Edit Channel -> Region Override`
> 
> How did you change this region? where? I cant edit a voice channel settings

This is done on Voice Channel settings on discord.

![image](https://user-images.githubusercontent.com/65385476/134654900-9bd1b9ef-de46-414d-a6f8-0ce7c4a9e437.png)

**Comment by x5engine** [comment]
> > I have this
> > const intents = new Discord.Intents(32767);
> > const discordClient = new Discord.Client({ intents });
> > const resource = createAudioResource('./Song' + randomId + '.mp3', {
> > inputType: StreamType.Arbitrary,
> > });
> > player.play(resource);
> > try {
> > await entersState(player, AudioPlayerStatus.Playing, 5_000);
> > // The player has entered the Playing state within 5 seconds
> > console.log('Playback has started!');
> > } catch (error) {
> > // The player has not entered the Playing state and either:
> > // 1) The 'error' event has been emitted and should be handled
> > // 2) 5 seconds have passed
> > console.error(error);
> > }
> 
> Where is connection.subscribe ??

what connection.subscribe?


I have this too

const player = createAudioPlayer();

then i do this to join user channel
        joinVoiceChannel({
            channelId: message.member.voice.channel.id,
            guildId: message.member.voice.channel.guild.id,
            adapterCreator: message.member.voice.channel.guild.voiceAdapterCreator
        })

**Comment by x5engine** [comment]
> > > `Edit Channel -> Region Override`
> > 
> > 
> > How did you change this region? where? I cant edit a voice channel settings
> 
> This is done on Voice Channel settings on discord.
> 
> ![image](https://user-images.githubusercontent.com/65385476/134654900-9bd1b9ef-de46-414d-a6f8-0ce7c4a9e437.png)

how do I access this?

**Comment by killer069** [comment]
@x5engine 

Read docs first and then create issue. [here](https://discordjs.guide/voice/audio-player.html#playing-audio)

**Comment by killer069** [comment]
> > > > `Edit Channel -> Region Override`
> > > 
> > > 
> > > How did you change this region? where? I cant edit a voice channel settings
> > 
> > 
> > This is done on Voice Channel settings on discord.
> > ![image](https://user-images.githubusercontent.com/65385476/134654900-9bd1b9ef-de46-414d-a6f8-0ce7c4a9e437.png)
> 
> how do I access this?

Just go to Voice Channel settings by clicking on gear besides Voice channel name
![image](https://user-images.githubusercontent.com/65385476/134655405-ae89f0e4-3a23-4c34-b29b-b7fadd765001.png)

**Comment by x5engine** [comment]
> @x5engine
> 
> Read docs first and then create issue. [here](https://discordjs.guide/voice/audio-player.html#playing-audio)

thanks bro it works now :D. 


merci beaucoup

**Comment by x5engine** [comment]
can I play an audio from a url?

**Comment by killer069** [comment]
> can I play an audio from a url?

Yes you can but make sure you have global FFmpeg, not ffmpeg-static.

**Comment by killer069** [comment]
> can I play an audio from a url?

Yes you can but make sure you have global FFmpeg, not ffmpeg-static.

**Comment by Zebiano** [comment]
I just want to leave some tips of things I had to solve to get the bot running on windows, maybe it helps someone.
- I've successfully got the bot playing music with `"ffmpeg-static": "^4.4.0"` (unless I have installed `ffmpeg` in the past, though I did not find anything in my `env` variables).
- Make sure to make use of the `GUILD_VOICE_STATES` Intent:
  ```const client = new Client({ intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_VOICE_STATES] })```
- Make sure to have at least one encryption library installed. I used `libsodium-wrappers`, as `sodium` builds are broken.

That was all for me. I'm currently running into an issue where a song stops playing after more a less the same amount of time. I've heard YouTube may stop streams on certain occasions, but I need to test this longer to make sure it's consistent and actually has to do with YouTube blocking streams.

Here is my dependency report:
```
Core Dependencies
- @discordjs/voice: 0.6.0
- prism-media: 1.3.2

Opus Libraries
- @discordjs/opus: 0.6.0
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: 0.7.9
- tweetnacl: not found

FFmpeg
- version: 4.4-essentials_build-www.gyan.dev      
- libopus: yes
```

Hope this helps!

**Comment by ThreonX** [comment]
@Zebiano 
adding this "highWaterMark option" to your ytdl command increases the buffer size to 100MB, for me it solved the problem to some degree.
`const stream = ytdl(video.url, {filter: 'audioonly',highWaterMark: 104857600 }); `

**Comment by killer069** [comment]
@Zebiano @ThreonX 

Shift to [play-dl](https://github.com/play-dl/play-dl), new library but very good in terms of handling errors. You will get almost no errors with this.

**Comment by Zebiano** [comment]
Thank you @ThreonX and @killer069 for both those tips, I will definitely take a look at them!

**Comment by bco2135** [comment]
try changed ```const resource = createAudioResource(path.resolve('commands/audiotest/resonance.mp3'));``` to ```const resource = createAudioResource(join(__dirname, 'commands/audiotest/resonance.mp3'));

**Comment by unclejoona** [comment]
I have found one of the solution. I had this same problem that it wouldn't play anything when it joined to the voice channel. I checked Audioplayers "statechange" and it seemed it went from playing instantly into autopause and the problem was I hadn't added Intents.FLAGS.GUILD_VOICE_STATES into client intents, so I added it and then it worked perfectly.I hope this helps you folks.

**Comment by jack3898** [comment]
Has anyone tried downgrading their @discordjs/opus version to `0.5.3`? I have been able top get audio playback with that version but I have not with `0.6.0`.
